POST http://localhost:3003/api/blogs/636520b9d5a9b9efc4f66817/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hcmNlbCIsImlkIjoiNjJkOTNiZTA1MjE3OWQ0MjUzMTE0Yjc2IiwiaWF0IjoxNjY3NTY3MTU5fQ.cOSJM96wOvu_Pp8p2oCYmRnggBnR-3kIEK38n2_PsVQ

{
  "comment": "Hello again"
}